export const USERLOGIN_REQUEST = "USERLOGIN_REQUEST";
export const USERLOGIN_RESPONSE = "USERLOGIN_RESPONSE";
export const USERLOGIN_FAILED = "USERLOGIN_FAILED";

export const USERSINUP_REQUEST = "USERSINUP_REQUEST";
export const USERSINUP_RESPONSE = "USERSINUP_RESPONSE";
export const USERSINUP_FAILED = "USERSINUP_FAILED";

export const vandoracount_REQUEST = "vandoracount_REQUEST";
export const vandoracount_RESPONSE = "vandoracount_RESPONSE";
export const vandoracount_FAILED = "vandoracount_FAILED";

export const LOADUSERDATA_REQUEST = "LOADUSERDATA_REQUEST";
export const LOADUSERDATA_RESPONSE = "LOADUSERDATA_RESPONSE";
export const LOADUSERDATA_FAILED = "LOADUSERDATA_FAILED";

export const USERUPDATE_REQUEST = "USERUPDATE_REQUEST";
export const USERUPDATE_RESPONSE = "USERUPDATE_RESPONSE";
export const USERUPDATE_FAILED = "USERUPDATE_FAILED";

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_RESPONSE = "CATEGORY_RESPONSE";
export const CATEGORY_FAILED = "CATEGORY_FAILED";

export const THEMELIST_REQUEST = "THEMELIST_REQUEST";
export const THEMELIST_RESPONSE = "THEMELIST_RESPONSE";
export const THEMELIST_FAILED = "THEMELIST_FAILED";


export const CLEAR_ERROR = "CLEAR_ERROR";
