export const BlogData = [
  {
    id: 1,
    image: "static/page3img2.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#F8B912",
    btnColor: "#F8B912",
    borderColor: "#F8B912",
  },
  {
    id: 2,
    image: "static/page3img3.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#027656",
    btnColor: "#027656",
    borderColor: "#027656",
  },
  {
    id: 3,
    image: "static/page3img4.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#66C0BE",
    btnColor: "#66C0BE",
    borderColor: "#66C0BE",
  },
];

export const BlogData1 = [
  {
    id: 1,
    image: "static/page3img5.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#901346",
    btnColor: "#901346",
    borderColor: "#901346",
  },
  {
    id: 2,
    image: "static/page3img6.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#00B0D7",
    btnColor: "#00B0D7",
    borderColor: "#00B0D7",
  },
  {
    id: 3,
    image: "static/page3img7.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#EC6877",
    btnColor: "#EC6877",
    borderColor: "#EC6877",
  },
  {
    id: 4,
    image: "static/page3img8.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#FF4304",
    btnColor: "#FF4304",
    borderColor: "#FF4304",
  }
];

export const BlogData2 = [
  {
    id: 1,
    image: "static/page3img10.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#901346",
    btnColor: "#901346",
    borderColor: "#901346",
  },
  {
    id: 2,
    image: "static/page3img11.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#00B0D7",
    btnColor: "#00B0D7",
    borderColor: "#00B0D7",
  },
  {
    id: 3,
    image: "static/page3img12.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#EC6877",
    btnColor: "#EC6877",
    borderColor: "#EC6877",
  },
  {
    id: 4,
    image: "static/page3img13.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#CA8BBB",
    btnColor: "#CA8BBB",
    borderColor: "#CA8BBB",
  },
  {
    id: 5,
    image: "static/page3img14.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#901346",
    btnColor: "#901346",
    borderColor: "#901346",
  },
  {
    id: 6,
    image: "static/page3img15.png",
    title: "Blog title",
    line: "Where | When | How many people ",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna...",
    btn: "DISCOVER MORE",
    titleColor: "#00B0D7",
    btnColor: "#00B0D7",
    borderColor: "#00B0D7",
  }
];
